"""
Email notification module for ML-based Network Monitoring System
Features:
- Sends high-severity threat alerts instantly
- Includes MITRE ATT&CK mapping
- Confidence score
- Dashboard deep-link
- Easy integration with Isolation Forest / classifier outputs
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


class EmailNotifier:
    def __init__(self, smtp_server, smtp_port, sender_email, sender_password):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.sender_email = sender_email
        self.sender_password = sender_password

    def send_threat_alert(self, recipient_email, alert_data):
        """
        alert_data example:
        {
            "severity": "CRITICAL",
            "title": "Privilege Escalation",
            "src_ip": "192.168.1.10",
            "dst_ip": "10.0.0.5",
            "classification": "Malicious Insider Activity",
            "mitre_tactic": "Privilege Escalation",
            "mitre_technique": "T1068 - Exploitation for Privilege Escalation",
            "confidence": 98.5,
            "dashboard_url": "http://localhost:5000/alerts/145",
            "timestamp": "2026-04-16 13:31:00"
        }
        """

        subject = f"[{alert_data['severity']}] ML Threat Alert - {alert_data['title']}"

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height:1.6;">
            <h2 style="color:red;">🚨 High Severity Threat Detected</h2>
            <p><strong>Attack Severity & Title:</strong> {alert_data['severity']}: {alert_data['title']}</p>
            <p><strong>Timestamp:</strong> {alert_data['timestamp']}</p>
            <hr>
            <p><strong>Source IP:</strong> {alert_data['src_ip']}</p>
            <p><strong>Destination IP:</strong> {alert_data['dst_ip']}</p>
            <p><strong>Attack Classification:</strong> {alert_data['classification']}</p>
            <p><strong>MITRE ATT&CK Tactic:</strong> {alert_data['mitre_tactic']}</p>
            <p><strong>MITRE ATT&CK Technique:</strong> {alert_data['mitre_technique']}</p>
            <p><strong>Model Confidence Score:</strong> {alert_data['confidence']}%</p>
            <hr>
            <p>
                <a href="{alert_data['dashboard_url']}"
                   style="background:#d32f2f;color:white;padding:10px 18px;text-decoration:none;border-radius:5px;">
                   View Full Alert in Dashboard
                </a>
            </p>
            <br>
            <p>This email was auto-generated by your ML-based Network Monitoring & Incident Response System.</p>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.sender_email
        msg["To"] = recipient_email
        msg.attach(MIMEText(html_body, "html"))

        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.sendmail(self.sender_email, recipient_email, msg.as_string())
            print("✅ Threat alert email sent successfully")
        except Exception as e:
            print(f"❌ Email sending failed: {e}")


# ---------------- INTEGRATION WITH ML PIPELINE ----------------
def process_ml_prediction(prediction, confidence, flow_data):
    """
    Example hook after your Isolation Forest / classifier prediction.
    prediction: detected attack label
    confidence: model confidence
    flow_data: packet/flow metadata
    """

    HIGH_SEVERITY_ATTACKS = [
        "Privilege Escalation",
        "DDoS",
        "Botnet",
        "Ransomware",
        "Brute Force"
    ]

    if prediction in HIGH_SEVERITY_ATTACKS and confidence > 95:
        mitre_map = {
            "Privilege Escalation": (
                "Privilege Escalation",
                "T1068 - Exploitation for Privilege Escalation"
            ),
            "DDoS": (
                "Impact",
                "T1498 - Network Denial of Service"
            ),
            "Brute Force": (
                "Credential Access",
                "T1110 - Brute Force"
            ),
        }

        tactic, technique = mitre_map.get(
            prediction,
            ("Discovery", "Unknown Technique")
        )

        alert = {
            "severity": "CRITICAL",
            "title": prediction,
            "src_ip": flow_data["src_ip"],
            "dst_ip": flow_data["dst_ip"],
            "classification": prediction,
            "mitre_tactic": tactic,
            "mitre_technique": technique,
            "confidence": round(confidence, 2),
            "dashboard_url": f"http://localhost:5000/alerts/{flow_data['alert_id']}",
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        notifier = EmailNotifier(
            smtp_server="smtp.gmail.com",
            smtp_port=587,
            sender_email="your_email@gmail.com",
            sender_password="your_app_password"
        )

        notifier.send_threat_alert(
            recipient_email="admin@company.com",
            alert_data=alert
        )


# ---------------- DEMO TEST ----------------
if __name__ == "__main__":
    sample_flow = {
        "src_ip": "172.16.0.12",
        "dst_ip": "10.10.1.5",
        "alert_id": 501
    }

    process_ml_prediction(
        prediction="Privilege Escalation",
        confidence=98.5,
        flow_data=sample_flow
    )
